name: build-wheel

on:
  push:
    tags: ["v*"]
  workflow_dispatch: {}

jobs:
  wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14]          # AppleSilicon runner
    steps:
      - uses: actions/checkout@v4

      # gfortran
      - name: Install gfortran
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y gfortran
      - name: Install gfortran (macOS)
        if: matrix.os == 'macos-14'
        run: brew install gcc        # gfortran を含む

      # cibuildwheel
      - uses: actions/setup-python@v5
        with: {python-version: "3.12"}         # ビルド用 Python 1 つ
      - run: python -m pip install cibuildwheel numpy
      - name: Build wheels
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
          CIBW_SKIP: "*-win32 *-manylinux_i686"
          CIBW_ENVIRONMENT: "FC=gfortran"
        run: cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4        # ← v4 !!
        with:
          name: wheel-${{ matrix.os }}
          path: wheelhouse/*.whl
