name: Build wheels

on:
  push:
    tags: ["v*"]          # バージョンタグを打ったときに実行
  workflow_dispatch: {}   # 手動実行も可

jobs:
  build:
    name: ${{ matrix.os }}-py${{ matrix.py }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        py: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      # Fortranコンパイラのセットアップ
      - name: Setup Fortran compiler
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran

      - name: Setup Fortran compiler (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install gfortran

      - name: Setup Fortran compiler (Windows)
        if: matrix.os == 'windows-latest'
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: gcc

      # F2PYの依存関係をインストール
      - name: Install F2PY dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy meson ninja

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BUILD: cp${{ matrix.py }}-*
          CIBW_SKIP: "*-win32 *-manylinux_i686"
          # Fortranサポートのための環境変数
          CIBW_BEFORE_BUILD: pip install numpy meson ninja
          CIBW_ENVIRONMENT_LINUX: "FC=gfortran"
          CIBW_ENVIRONMENT_MACOS: "FC=gfortran"
          CIBW_ENVIRONMENT_WINDOWS: "FC=gfortran"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl